import { initFirebase } from "@/firebase/firebaseApp";
import NavBar from "./components/NavBar/NavBar";
import SideBar from "./components/SideBar/SideBar";
import { getAuth, signInWithPopup, GoogleAuthProvider } from "firebase/auth";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex">
        <SideBar />
        <div className="flex-col w-full">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
